export default {
    background:[{
        _id: '1',
        image: '',
        alt: '',
    },
    {
        _id: '2',
        image: '',
        alt: '',
    },
    {
        _id: '3',
        image: '',
        alt: '',
    },
    {
        _id: '4',
        image: '',
        alt: '',
    },{
        _id: '5',
        image: '',
        alt: '',
    }],

    reservations: [{
        _id: '1',
        clientName: 'Sally K.',
        clientLocation: 'Minnesota',
        gender: 'female',
        litter: 'next litter',
        litterETA: '12/10/20',
        reserved: 'yes'
    },
    {
        _id: '2',
        clientName: 'Kathy C.',
        clientLocation: 'California',
        gender: 'male or female',
        litter: 'next litter',
        litterETA: '12/10/20',
        reserved: 'yes'
    }],
    puppies: [{
        _id: '1',
        puppyName: 'Emma',
        dob: '05/10/20',
        rank: 'Adopted', //Adopted or Available
        color: 'Red-Brindle',
        birthWeight: '',
        birthTime: '',
        momsName: 'Daphne',
        dadsName: 'Cocoa',
        icon: '',
        video: 'N/A',
        gender: 'Female',
        slideimage1: '',
        slideimage2: '',
        slideimage3: '',
        slideimage4: '',
        discription: 'Adventurious, Playful, Joyful little girl puppy',
        price: '2900',
        priceincludes: '',
        priceincludesTwo: '',
        reg: 'Limited Akc Registration',
        AdpotedFamily: 'Mike'
    },
    {
        _id: '2',
        puppyName: 'Leo',
        dob: '05/10/20',
        rank: 'Adopted', //Adopted or Available
        color: 'Black-Brindle',
        birthWeight: '',
        birthTime: '',
        momsName: '',
        dadsName: '',
        icon: '',
        video: 'N/A',
        gender: 'Male',
        slideimage1: '',
        slideimage2: '',
        slideimage3: '',
        slideimage4: '',
        price: '2400',
        priceincludes: '',
        priceincludesTwo: '',
        reg: 'Limited Akc Registration',
        AdpotedFamily: 'Natalie'
    },
    {
        _id: '3',
        puppyName: 'Milo',
        dob: '05/10/20',
        rank: 'Adopted', //Adopted or Available
        color: 'Wheaton',
        birthWeight: '',
        birthTime: '',
        momsName: '',
        dadsName: '',
        icon: '',
        video: 'N/A',
        gender: 'Male',
        slideimage1: '',
        slideimage2: '',
        slideimage3: '',
        slideimage4: '',
        discription: 'Adventurious, Playful, Joyful little girl puppy',
        price: '2400',
        priceincludes: '',
        priceinclude: '',
        priceincludesTwo: '',
        reg: 'Limited Akc Registration',
        AdpotedFamily: 'Kaia'
    }],
  
};